// array of objects with information to pull for flash cards
var flashCards = [
  { title: "Technology",
    front: "The most popular search engine",
    frontImage: "images/books-glasses.jpg",
    backImage: "images/google.jpg",
    back: "Google"},
  { title: "Technology",
    front: "A connected group of pages on the internet.",
    frontImage: "images/computer-site.jpg",
    backImage: "images/website.jpg",
    back: "Website"},
  { title: "Technology",
    front: "A way to access the internet that's commonly used for mobile devices.",
    frontImage: "images/smart-phone.jpg",
    backImage: "images/wifi.jpg",
    back: "Wifi"},
  { title: "Technology",
    front: "The name of the address used to visit websites.",
    frontImage: "images/address.jpg",
    backImage: "images/keyboard.jpg",
    back: "URL"},
  { title: "Technology",
    front: "Name of the window used to access the internet.",
    frontImage: "images/window.jpg",
    backImage: "images/browsers.jpg",
    back: "Browser"},
  { title: "Technology",
    front: "An electronic device used for storing and processing data.",
    frontImage: "images/computer.jpg",
    backImage: "images/computers.jpg",
    back: "Computer"},
  { title: "Technology",
    front: "Typically a small, specialized program downloaded onto mobile devices.",
    frontImage: "images/uber.jpg",
    backImage: "images/app.jpg",
    back: "App"},
  { title: "Technology",
    front: "A popular website used to stream movies.",
    frontImage: "images/movie.jpg",
    backImage: "images/netflix.jpg",
    back: "Netflix"},
  { title: "Social Media",
    front: "A popular website used to share and watch movie clips and videos.",
    frontImage: "images/make-movie.jpg",
    backImage: "images/youtube.jpg",
    back: "YouTube"},
  { title: "Social Media",
    front: "A popular social media website known for 'friending' people you know, sharing photos, links, and interacting with other people's posts.",
    frontImage: "images/computer-f.jpg",
    backImage: "images/facebook.jpg",
    back: "Facebook"},
  { title: "Social Media",
    front: "A popular social media website known for 'tweeting,' or sharing posts that are 140 characters or less.",
    frontImage: "images/mobile-t.jpg",
    backImage: "images/twitter.jpg",
    back: "Twitter"},
  { title: "Technology",
    front: "A popular site used for sending/receiving payments online. It's often used with Ebay.",
    frontImage: "images/credit-card.jpg",
    backImage: "images/paypal.jpg",
    back: "PayPal"},
  { title: "Social Media",
    front: "A popular app/website used for quickly sending and receiving payments for free.",
    frontImage: "images/credit-card-2.jpg",
    backImage: "images/venmo.jpg",
    back: "Venmo"},
  { title: "Technology",
    front: "A popular website used for posting listings (i.e. housing, furniture for sale)",
    frontImage: "images/listings.jpg",
    backImage: "images/craigslist.jpg",
    back: "Craigslist"},
  { title: "Technology",
    front: "A website used for buying or selling items in an auction.",
    frontImage: "images/auction.jpg",
    backImage: "images/ebay.jpg",
    back: "Ebay"},
  { title: "Technology",
    front: "A desktop application that enables configuring one or more email addresses to receive, read, compose and send emails.",
    frontImage: "images/email-client.jpg",
    backImage: "images/outlook.jpg",
    back: "Email client"},
  { title: "Technology",
    front: "Best practice for ensuring that your computer programs are up-to-date.",
    frontImage: "images/update.jpg",
    backImage: "images/windows-update.jpg",
    back: "Updating software"},
  { title: "Technology",
    front: "With this, we're able to access websites and web applications.",
    frontImage: "images/site.jpg",
    backImage: "images/wires.jpg",
    back: "Internet"}
]
