// array of objects with information to pull for flash cards
var flashCards = [
  { title: "Technology",
    front: "The most popular search engine",
    frontImage: "images/books-glasses.jpg",
    back: "Google"},
  { title: "Technology",
    front: "A connected group of pages on the internet.",
    frontImage: "images/computer-site.jpg",
    back: "Website"},
  { title: "Technology",
    front: "A way to access the internet that's commonly used for mobile devices.",
    frontImage: "images/smart-phone.jpg",
    back: "Wifi"},
  { title: "Technology",
    front: "The name of the address used to visit websites.",
    frontImage: "images/address.jpg",
    back: "URL"},
  { title: "Technology",
    front: "Name of the window used to access the internet.",
    frontImage: "images/books-glasses.jpg",
    back: "Browser"},
  { title: "Technology",
    front: "An electronic device used for storing and processing data.",
    frontImage: "images/computer.jpg",
    back: "Computer"},
    { title: "Technology",
      front: "Typically a small, specialized program downloaded onto mobile devices.",
      frontImage: "images/app.jpg",
      back: "App"},
  { title: "Technology",
    front: "With this, we're able to access websites and web applications.",
    frontImage: "images/site.jpg",
    back: "Internet"}
]
